### ISSUE TITLE
no info on how to setup 

### ISSUE THREAD

**Issue by padima2** [database64128/swgp-go#22] opened 2022-10-21 08:31 UTC
my wg server on ubuntu was working well until the country decide to activate the dpi.now it s impossible to get wireguard get working.
i have windows and android in client side.
can you provide a step by step guide so it can help people wich are in my case as well

thank you for your time

**Comment by database64128** [comment] 2022-10-21 08:46
Duplicate of #21.

**Closed by database64128** 2022-10-21 08:46 UTC
